### ISSUE TITLE
Feature: max brightness

### ISSUE THREAD

**Issue by tacsist** [night-crawler/led_matrix_monitoring#3]
Hi, me again. No problem this time, but a feature request. On my anecdotal findings running both matrices takes about 10W which is noticeable amount when running on battery. I think having an option to set max brightness value to the monitoring/(maybe daemon is better for this) to limit the powerdraw. And probably let external scripts handle toggling preferred value depending on AC/bat.

**Comment by night-crawler** [comment]
Hi,

I added new config parameters in `/etc/led_matrix/monitoring.toml`:

```toml
[render]
...
max_brightness = 255
max_brightness_file = "/etc/led_matrix/max_brightness_value"
```

The `max_brightness_value` is read every render cycle, `max_brightness` can be used to specify statically the value.
Please, try it out and feel free to close the issue it works fine for you.

Thanks!
